version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.12.1-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/
      - ./rabbitmq/log:/var/log/rabbitmq
    networks:
      - npm-nw

networks:
  npm-nw:
    external: true
